-- MySQL Script generated by MySQL Workbench
-- 12/27/17 08:43:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`anexo` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`categoria` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`usuario` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `LOGIN` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `TIPO` ENUM('A', 'P', 'T', 'D') NOT NULL DEFAULT 'A' COMMENT '\'A\'- Aluno, \'P\'- Professor, \'T\'- Ambos, aluno e professor',
  `AVATAR` ENUM('RE', 'RA', 'IO', 'IA', 'PE') NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`curso` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `ASSUNTO_GERAL` VARCHAR(5000) NULL DEFAULT NULL,
  `COD_ACESSO` VARCHAR(10) NOT NULL,
  `USUARIO_ID` INT(11) NOT NULL,
  `ANEXO_ID` INT(11) NULL DEFAULT NULL,
  `SITUACAO` ENUM('R', 'C') NOT NULL COMMENT '\'R\'-Rascunho, \'C\'-Completo',
  `categoria_ID` INT(11) NOT NULL,
  `DISPONIBILIDADE` ENUM('A', 'F', 'E') NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CURSO_USUARIO1_idx` (`USUARIO_ID` ASC),
  INDEX `fk_CURSO_ANEXO1_idx` (`ANEXO_ID` ASC),
  INDEX `fk_curso_categoria1_idx` (`categoria_ID` ASC),
  CONSTRAINT `fk_CURSO_ANEXO1`
    FOREIGN KEY (`ANEXO_ID`)
    REFERENCES `tcc`.`anexo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `tcc`.`usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_categoria1`
    FOREIGN KEY (`categoria_ID`)
    REFERENCES `tcc`.`categoria` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`curso_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`curso_aluno` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `POSICAO_ATUAL` INT(11) NOT NULL,
  `PONTUACAO` INT(11) NOT NULL,
  `SITUACAO` ENUM('A', 'C') NOT NULL COMMENT '\'A\'-Em Andamento, \'C\'-Concluído',
  `CURSO_ID` INT(11) NOT NULL,
  `USUARIO_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CURSO_ALUNO_CURSO1_idx` (`CURSO_ID` ASC),
  INDEX `fk_CURSO_ALUNO_USUARIO1_idx` (`USUARIO_ID` ASC),
  CONSTRAINT `fk_CURSO_ALUNO_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `tcc`.`curso` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CURSO_ALUNO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `tcc`.`usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`etapa` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ASSUNTO` VARCHAR(5000) NOT NULL,
  `NIVEL` INT(11) NOT NULL,
  `JOGO` ENUM('Q', 'A', 'F', 'C') NOT NULL COMMENT 'Tipo de Jogo: \'Q\'-Quiz, \'A\'-Aposta, \'F\'-Forca, \'C\'-Caça Palavras',
  `CURSO_ID` INT(11) NOT NULL,
  `ANEXO_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ETAPA_CURSO1_idx` (`CURSO_ID` ASC),
  INDEX `fk_ETAPA_ANEXO1_idx` (`ANEXO_ID` ASC),
  CONSTRAINT `fk_ETAPA_ANEXO1`
    FOREIGN KEY (`ANEXO_ID`)
    REFERENCES `tcc`.`anexo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ETAPA_CURSO1`
    FOREIGN KEY (`CURSO_ID`)
    REFERENCES `tcc`.`curso` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`etapa_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`etapa_aluno` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PONTUACAO` INT(11) NOT NULL,
  `ETAPA_ID` INT(11) NOT NULL,
  `CURSO_ALUNO_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ETAPA_ALUNO_ETAPA1_idx` (`ETAPA_ID` ASC),
  INDEX `fk_ETAPA_ALUNO_CURSO_ALUNO1_idx` (`CURSO_ALUNO_ID` ASC),
  CONSTRAINT `fk_ETAPA_ALUNO_CURSO_ALUNO1`
    FOREIGN KEY (`CURSO_ALUNO_ID`)
    REFERENCES `tcc`.`curso_aluno` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ETAPA_ALUNO_ETAPA1`
    FOREIGN KEY (`ETAPA_ID`)
    REFERENCES `tcc`.`etapa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pergunta` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(1000) NOT NULL,
  `USUARIO_ID` INT(11) NOT NULL,
  `JUSTIFICATIVA` VARCHAR(1000) NULL DEFAULT NULL,
  `ANEXO_ID` INT(11) NULL DEFAULT NULL,
  `TIPO` ENUM('ME', 'CL') NOT NULL COMMENT 'Tipo de Pergunta: \'ME\'-multiplas escolhas, \'CL\'-completar lacuna',
  `NIVEL` ENUM('F', 'M', 'D') NOT NULL COMMENT '\'F\'-fácil, \'M\'-médio, \'D\'-difícil',
  `DICA` VARCHAR(500) NULL DEFAULT NULL,
  `CATEGORIA_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PERGUNTA_USUARIO1_idx` (`USUARIO_ID` ASC),
  INDEX `fk_PERGUNTA_ANEXO1_idx` (`ANEXO_ID` ASC),
  INDEX `fk_pergunta_categoria1_idx` (`CATEGORIA_ID` ASC),
  CONSTRAINT `fk_PERGUNTA_ANEXO1`
    FOREIGN KEY (`ANEXO_ID`)
    REFERENCES `tcc`.`anexo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERGUNTA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `tcc`.`usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pergunta_categoria1`
    FOREIGN KEY (`CATEGORIA_ID`)
    REFERENCES `tcc`.`categoria` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`etapa_pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`etapa_pergunta` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `POSICAO` INT(11) NULL DEFAULT NULL,
  `ETAPA_ID` INT(11) NOT NULL,
  `PERGUNTA_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ETAPA_PERGUNTA_ETAPA1_idx` (`ETAPA_ID` ASC),
  INDEX `fk_ETAPA_PERGUNTA_PERGUNTA1_idx` (`PERGUNTA_ID` ASC),
  CONSTRAINT `fk_ETAPA_PERGUNTA_ETAPA1`
    FOREIGN KEY (`ETAPA_ID`)
    REFERENCES `tcc`.`etapa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ETAPA_PERGUNTA_PERGUNTA1`
    FOREIGN KEY (`PERGUNTA_ID`)
    REFERENCES `tcc`.`pergunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 350
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`relatorio_etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`relatorio_etapa` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PONTUACAO` VARCHAR(45) NULL DEFAULT NULL,
  `ETAPA_ALUNO_ID` INT(11) NOT NULL,
  `GANHOU` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_relatorio_etapa_etapa_aluno1_idx` (`ETAPA_ALUNO_ID` ASC),
  CONSTRAINT `fk_relatorio_etapa_etapa_aluno1`
    FOREIGN KEY (`ETAPA_ALUNO_ID`)
    REFERENCES `tcc`.`etapa_aluno` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`resposta` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(1000) NOT NULL,
  `CORRETA` VARCHAR(1) NOT NULL,
  `PERGUNTA_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RESPOSTA_PERGUNTA1_idx` (`PERGUNTA_ID` ASC),
  CONSTRAINT `fk_RESPOSTA_PERGUNTA1`
    FOREIGN KEY (`PERGUNTA_ID`)
    REFERENCES `tcc`.`pergunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 94
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`pergunta_etapa_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pergunta_etapa_aluno` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PONTUACAO` INT(11) NOT NULL,
  `PULO` VARCHAR(1) NOT NULL,
  `DICA` VARCHAR(1) NOT NULL,
  `TEMPO_ACABOU` VARCHAR(1) NULL DEFAULT NULL,
  `APOSTAS` VARCHAR(45) NULL DEFAULT NULL,
  `PERGUNTA_ID` INT(11) NOT NULL,
  `RELATORIO_ETAPA_ID` INT(11) NOT NULL,
  `RESPOSTA_ESCOLHIDA_ID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PERGUNTA_ALUNO_PERGUNTA1_idx` (`PERGUNTA_ID` ASC),
  INDEX `fk_pergunta_etapa_aluno_relatorio_etapa1_idx` (`RELATORIO_ETAPA_ID` ASC),
  INDEX `fk_pergunta_etapa_aluno_resposta1_idx` (`RESPOSTA_ESCOLHIDA_ID` ASC),
  CONSTRAINT `fk_PERGUNTA_ALUNO_PERGUNTA1`
    FOREIGN KEY (`PERGUNTA_ID`)
    REFERENCES `tcc`.`pergunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pergunta_etapa_aluno_relatorio_etapa1`
    FOREIGN KEY (`RELATORIO_ETAPA_ID`)
    REFERENCES `tcc`.`relatorio_etapa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pergunta_etapa_aluno_resposta1`
    FOREIGN KEY (`RESPOSTA_ESCOLHIDA_ID`)
    REFERENCES `tcc`.`resposta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 152
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
